### ISSUE TITLE
Dependency errors..

### ISSUE THREAD

**Issue by asyncthreading** [PrimusLV/FactionsPE#4]
I dropped the plugin on my server, and when i started the server i got these errors.

Tesseract] [18:40:32] [Server thread/CRITICAL]: Could not load plugin 'FactionsPE'                           [Tesseract] [18:40:32] [Server thread/CRITICAL]: Could not load plugin 'FactionsPE': Unknown dependency                                                                             [Tesseract] [18:40:32] [Server thread/CRITICAL]: Could not load plugin 'FactionsPE': Circular dependency detected 

Ps: i have EconomyAPI, killrate and simpleauth.

**Comment by buchwasa** [comment]
You need to have EvalCore as well

**Comment by asyncthreading** [comment]
how can i get it..

**Comment by Kris-Driv** [comment]
Hi. I'm working on this project and in soon days this dependency will be removed. Check out at https://github.com/Chris-Prime/FactionsPE

**Comment by asyncthreading** [comment]
Ok, but when is the dependency removed exactly? And the plugin will have /f map and /f chat?? Ty

**Comment by buchwasa** [comment]
Also @Uniqulmuia pretty fancy that you use Tesseract

**Comment by PrimusLV** [comment]
FactionsPE is basically "Factions" port from Bukkit. The dependency is partly removed, but there are still many bugs that must be fixed in order to make a release.

**Comment by asyncthreading** [comment]
How much takes to be released? I want to use it on my server, and to let ur credits on it

**Comment by PrimusLV** [comment]
I'm not promising but I'll try to release it around new year

**Comment by asyncthreading** [comment]
dammit, ok..

**Comment by PrimusLV** [comment]
I have inspired some other developers to create a faction plugin, try it [UltraFaction](https://github.com/PocketEssential/UltraFaction)

**Comment by asyncthreading** [comment]
I already tryed it, but i shows retarded errors

**Comment by PrimusLV** [comment]
Help them by reporting those errors

**Comment by asyncthreading** [comment]
btw i m waiting for ur plugin :D bye
